pool:
  vmImage: 'vs2017-win2016' 
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs: 
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: true 

- script: |
    dotnet test dotnetcore-tests --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../.coverage/
    cd dotnetcore-tests
    dotnet reportgenerator "-reports:..\.coverage\coverage.cobertura.xml" "-targetdir:..\.coverage\report" -reportTypes:htmlInline 

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from .coverage/**/*.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '.coverage/**/*.xml'
    reportDirectory: .coverage/report


